---
title: "LAB"
output: html_document
---
# 1. Line Graph
```{r}
library(dplyr)
library(readr)
library(ggplot2)
csu <- read_table2("CSU.dat", col_names = FALSE) %>% data.frame
ggplot(data = csu, aes(x = X1, y = X3)) + 
  geom_line(color = "red") + 
  geom_hline(yintercept = median(csu$X3), linetype = 2) + 
  theme_classic() + 
  ggtitle("Cal State Undergraduate Resident Tuition and Fees 1992−2017") +
  xlab("Year") + ylab("Dollars") +
  scale_x_continuous(breaks = seq(1992, 2017, 2)) +
  scale_y_continuous(breaks = seq(0,6000,1000), limits = c(0,6000)) +
  theme(axis.text.x=element_text(size=10), 
        plot.title=element_text(hjust=0.5,size=16,face="bold"), 
        panel.border=element_rect(fill=NA))
```

# 2. Boxplot
```{r}
library(readr)
ND <- read_csv("http://www.stat.ucla.edu/~vlew/datasets/ND.csv")
SF <- read_csv("http://www.stat.ucla.edu/~vlew/datasets/SF.csv")
ND$TFAVG <- (ND$TAVG * 1.8 )+ 32
ND$STATE <- "North Dakota"
SF$TFAVG <- (SF$TAVG * 1.8 )+ 32
SF$STATE <- "San Francisco"
NDSF <- rbind(ND, SF)
ggplot(NDSF, aes(x = factor(MO), y = TFAVG, fill = STATE)) + 
  geom_boxplot() + 
  ggtitle("Boxplot Example - Temperature Data") +
  xlab("Month") + ylab("Temperature") + theme_classic() +
  theme(legend.position = c(0.5,0.2),
        legend.background = element_rect(linetype = 1, color= "black"),
        legend.title = element_blank())
```

# 3. Histogram
```{r fig.height= 7}
library(gridExtra)
yelp3 <- read_csv("http://www.stat.ucla.edu/~vlew/datasets/yelp3.csv")
g1 <- ggplot(yelp3[yelp3$categories.0=="Buffets",], aes(x= stars, y=..density..)) + 
  geom_histogram(binwidth = 0.5, fill = "blue", color = "black") + theme_classic() + 
  xlab("Yelp Rating") + ggtitle("Histogram Eample - Buffets") +
  theme(plot.title=element_text(hjust=0.5,size=16,face="bold")) 
g2 <- ggplot(yelp3[yelp3$categories.0=="Vegan",], aes(x= stars, y=..density..)) + 
  geom_histogram(binwidth = 0.5, fill = "orange", color = "black") + theme_classic() + 
  xlab("Yelp Rating") + ggtitle("Histogram Eample - Vegan") +
  theme(plot.title=element_text(hjust=0.5,size=16,face="bold")) 
g3 <- ggplot(yelp3[yelp3$categories.0=="Sports Bars",], aes(x= stars, y=..density..)) + 
  geom_histogram(binwidth = 0.5, fill = "maroon", color = "black") + theme_classic() + 
  xlab("Yelp Rating") + ggtitle("Histogram Eample - Sports Bars") +
  theme(plot.title=element_text(hjust=0.5,size=16,face="bold")) 
grid.arrange(g2, g1, g3)
```

# 4. scatter plots
A.
```{r}
library(GGally)
ggpairs(midwest[,c(5,10,18,20,23)], axisLabels = "internal",
        title = "Scatterplot Matrix of ggplot dataset midwest",
        upper = list(continuous = "points"), ) +
  theme_classic()
```

B.
```{r}
ggplot(midwest, aes(x = perchsd, y= percollege, col = factor(state))) +
  geom_point(size = 0.5) +
  geom_hline(yintercept = median(midwest$percollege), col = "red") +
  geom_vline(xintercept = median(midwest$perchsd), col = "blue") +
  ggtitle("Plot of College degree on high school diploma with medians") +
  theme_classic() + 
  scale_color_manual(values = c("black", "red", "green", "blue", "cyan")) +
  theme(plot.title=element_text(hjust=0.5,size=16,face="bold"), 
        panel.border=element_rect(fill=NA),
        legend.position = c(0.045,0.8),
        legend.title = element_blank(),
        legend.background = element_rect(linetype = 1, colour = "black"))
```

# 5. Multiple Lines and legends
```{r}
ggplot(data = csu, aes(x = X1, y = X3, color = "blue")) + 
  geom_line() + 
  geom_hline(yintercept = median(csu$X3)) +
  geom_line(data = csu, aes(x = X1, y = X12, color = "red"), linetype = 2) + 
  geom_hline(yintercept = median(csu$X12), linetype = 2) + 
  ggtitle("CSU Tuition 1992-2017") +
  xlab("Year") +
  ylab("in Dollars") +
  theme_classic() +
  scale_x_continuous(breaks = seq(1992, 2016, 3)) +
  scale_y_continuous(breaks = seq(0, 12000, 2000), limits = c(0, 12000))+
  scale_color_manual(values = c("blue","red"), labels = c("Resident", "Non-resident")) + 
  theme(axis.text.x=element_text(size=10), 
        plot.title=element_text(hjust=0.5, size=16, face="bold"), 
        panel.border=element_rect(fill=NA),
        legend.position = c(0.5,0.5),
        legend.background = element_rect(linetype = 1, color = "black"),
        legend.title = element_blank())
```
